[project]
name = 'stacks-tasks-and-reputation-protocol'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.task-reputation-protocol]
path = 'contracts/task-reputation-protocol.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
